### PR TITLE
sdk 47

### PR DESCRIPTION
**Pull request by faddat**
- replace tendermint and tm-db.  make proto-gen

### CODE REVIEW

**Comment by hxrts** [comment]
@faddat just want to say THANK YOU for doing this. incredibly important work for the ecosystem.

**Comment by faddat** [comment]
Sir, @pysel  is like that <3

**Comment by faddat** [comment]
You know if I had to guess, you might want to look into the proto files a little more. 47 introduced some changes and we have some match them more or less well we have to match them with the changes from here

**Comment by faddat** [comment]
This.... just might have it done.

**Pull request closed without merging**
